# -*- coding: utf-8 -*-
"""toxic_content_classification

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T2PunjupjkSBFd7xEmQeUghhTMnL__4O
"""

import pandas as pd
import numpy as np

df = pd.read_excel("/content/NLP_Neurova_toxic_content_classification (3).xlsx")

print(df.shape)

print(df.head())

print(df.info())

df.columns

df.isnull().sum()

df.duplicated().sum()

df = df.drop_duplicates()

df['image descriptions'].value_counts()

df['image descriptions'].duplicated().sum()

df.duplicated().sum()

df['query'].value_counts()

df['Toxic Category'].value_counts()

import matplotlib.pyplot as plt

df["Toxic Category"].value_counts().plot(kind="bar", figsize=(12,6))
plt.xticks(rotation=45)
plt.show()

print(df["query"].duplicated().sum())

df = df.drop_duplicates(subset=["query"])

print(df["Toxic Category"].unique())

df["full_text"] = (
    df["query"].astype(str) + " " +
    df["image descriptions"].astype(str)
)

print(df["full_text"].head())

print(df['full_text'].str.split().apply(len).describe())

print(df["full_text"].duplicated().sum())

import re
import string

def clean_text(text):
    text = str(text).lower()

    # remove urls
    text = re.sub(r"http\S+|www\S+|https\S+", '', text)

    # remove html tags
    text = re.sub(r'<.*?>', '', text)

    # remove punctuation
    text = text.translate(str.maketrans('', '', string.punctuation))

    # remove numbers
    text = re.sub(r'\d+', '', text)

    # remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()

    return text

df["clean_text"] = df["full_text"].apply(clean_text)

print(df[["full_text", "clean_text"]].head())

df.head(1)

print(df.shape)
print(df["Toxic Category"].value_counts())
print(df[["clean_text", "Toxic Category"]].head())

class_counts = df["Toxic Category"].value_counts()

rare_classes = [
    "Suicide & Self-Harm",
    "Elections",
    "Sex-Related Crimes",
    "Child Sexual Exploitation"
]

print(rare_classes)

import random

def augment_text(text):
    words = text.split()

    if len(words) < 4:
        return text

    aug_type = random.choice([
        "delete",
        "swap"
    ])

    if aug_type == "delete":
        idx = random.randint(0, len(words)-1)
        words.pop(idx)

    elif aug_type == "swap":
        idx1 = random.randint(0, len(words)-2)
        idx2 = idx1 + 1
        words[idx1], words[idx2] = words[idx2], words[idx1]

    return " ".join(words)

target_count = 30

augmented_rows = []

for class_name in rare_classes:

    class_df = df[df["Toxic Category"] == class_name]

    current_count = len(class_df)

    needed = target_count - current_count

    for _ in range(needed):

        sample_row = class_df.sample(1).iloc[0].copy()

        sample_row["clean_text"] = augment_text(
            sample_row["clean_text"]
        )

        augmented_rows.append(sample_row)

import pandas as pd

augmented_df = pd.DataFrame(
    augmented_rows
)

df_final = pd.concat(
    [df, augmented_df],
    ignore_index=True
)

df_final['Toxic Category'].value_counts()

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

df_final["label"] = label_encoder.fit_transform(
    df_final["Toxic Category"]
)

from tensorflow.keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer(
    num_words=20000,
    oov_token="<OOV>"
)

tokenizer.fit_on_texts(
    df_final["clean_text"]
)

sequences = tokenizer.texts_to_sequences(
    df_final["clean_text"]
)

max_length = 35

from tensorflow.keras.preprocessing.sequence import pad_sequences

X = pad_sequences(
    sequences,
    maxlen=max_length,
    padding="post",
    truncating="post"
)

y = df_final["label"].values

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

from sklearn.utils.class_weight import compute_class_weight
import numpy as np

classes = np.unique(y_train)

class_weights = compute_class_weight(
    class_weight="balanced",
    classes=classes,
    y=y_train
)

class_weights_dict = dict(
    zip(classes, class_weights)
)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Bidirectional, Dense, Dropout
from tensorflow.keras.optimizers import Adam

model = Sequential([
    Embedding(
        input_dim=20000,
        output_dim=128,
        input_length=35
    ),

    Bidirectional(
        LSTM(128, return_sequences=True)
    ),

    Bidirectional(
        LSTM(64)
    ),

    Dropout(0.5),

    Dense(64, activation="relu"),

    Dropout(0.3),

    Dense(9, activation="softmax")
])

model.summary()

optimizer = Adam(
    learning_rate=0.0005
)

model.compile(
    optimizer=optimizer,
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

# Reuse the early stopping and learning rate reduction callbacks
early_stopping = EarlyStopping(
    monitor='val_loss',
    patience=3,
    restore_best_weights=True
)
reduce_lr= ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.2,
    patience=2
)

history = model.fit(
    X_train,
    y_train,
    epochs=25,
    batch_size=16,
    validation_split=0.2,
    class_weight=class_weights_dict,
    callbacks=[early_stopping, reduce_lr]
)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay

y_pred_probs = model.predict(X_test)
y_pred = y_pred_probs.argmax(axis=1)

print("Accuracy (Simple Model):", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

for i, label in enumerate(label_encoder.classes_):
    print(i, label)

problem_class = label_encoder.inverse_transform([6])[0]

print(problem_class)

df[df["Toxic Category"] == problem_class][
    "clean_text"
].head(20)

ConfusionMatrixDisplay.from_predictions(
    y_test,
    y_pred
)
plt.title('Confusion Matrix (Simple Model)')
plt.show()

##########################################

model.save("toxic_model.keras")

import pickle

with open("tokenizer.pkl", "wb") as f:
    pickle.dump(tokenizer, f)

with open("label_encoder.pkl", "wb") as f:
    pickle.dump(label_encoder, f)

config = {
    "max_length": 35,
    "num_words": 20000
}

with open("config.pkl", "wb") as f:
    pickle.dump(config, f)

def predict_text(query, image_description):

    full_text = str(query) + " " + str(image_description)

    cleaned_text = clean_text(full_text)

    sequence = tokenizer.texts_to_sequences([cleaned_text])

    # 4. padding
    padded = pad_sequences(
        sequence,
        maxlen=max_length,
        padding="post",
        truncating="post"
    )

    # 5. prediction
    prediction = model.predict(padded)

    predicted_class = prediction.argmax(axis=1)[0]

    predicted_label = label_encoder.inverse_transform([predicted_class])[0]

    return predicted_label

result = predict_text(
    "How can I protect my house from criminals?",
    "a person breaking into a house"
)

print(result)

